### ISSUE TITLE
Missing some OG tags?

### ISSUE THREAD

**Issue by keitzer** [Tsukumogami-Software/milou#10]
Apparently according to `orcascan` (some open graph validator), we're still missing some OG tags:

<img width="495" alt="image" src="https://github.com/Tsukumogami-Software/milou/assets/8125837/a1e6d7c7-c5f1-4ef1-b96c-30ddecd931d8">

```
<meta property="og:locale" content="your value" />
<meta property="og:url" content="your value" />
<meta property="og:logo" content="your value" />
```

**Comment by zer0tonin** [comment]
This are now all implemented in 1.2.0 😄

- `og:locale` will use the `locale` attribute of each yml file ([example](https://github.com/Tsukumogami-Software/milou/blob/main/data/data.yml#L15))
- `og:url` will automaticall be set if the the `company.baseURL` attribute is set
- `og:logo` will use the first logo image if `company.baseURL` is set
