### ISSUE TITLE
OG Image needs a better relative URL

### ISSUE THREAD

**Issue by keitzer** [Tsukumogami-Software/milou#7]
using `1.1.1` with the new OG image tag.
And when I run it through a validator, i get :

```
https://www.pixeldiamondgames.com/./images/header.png
```
Yes technically the source image is relative to the generated index.html.... however, the folder itself is relative to the base domain at `/presskit/index.html` (and thus the image should be `/presskit/images/header.png`)

So it seems when the `<meta ...`> OG:image tag is being set up, the website crawler sees a relative URL and assumes top of domain.

Visual of failing to find the image
<img width="903" alt="image" src="https://github.com/Tsukumogami-Software/milou/assets/8125837/f36e779a-d0e7-44a0-85e9-ad63bf069e32">

even MORE complicated is the fact that -- the OG:image tag doesn't also account for the product itself

so the FULL url for the product's OG image is:
`domain.com/presskit/product/images/header.png`
but instead is generated as:
`domain.com/./images/header.png`
and even replacing the `.` in the product case with `/presskit` wouldn't send the right image either, it would send the company image and not the desired product image

**Comment by keitzer** [comment]
cc @zer0tonin

**Comment by keitzer** [comment]
When using chrome inspector to manually change the URL, it does exist in the right spot too:

<img width="481" alt="image" src="https://github.com/Tsukumogami-Software/milou/assets/8125837/c76cfa9a-aaad-4314-b134-d7ff0311f510">

**Comment by keitzer** [comment]
fwiw, i do have a `yarn` command that runs the build command, so I can know at time of generation what the relative URL will be:
```
yarn run milou build ./company --ignore-thumbnails --clean-build-folder --output build
# copy build folder to website's relative directory
```

**Comment by zer0tonin** [comment]
I think the only way to really mathc the spec is to provide an absolute URL.
It can be done using version 1.2.0 and by setting `baseURL` in the company yaml.
Like [here](https://github.com/Tsukumogami-Software/milou/blob/main/data/data.yml#L12)
