### ISSUE TITLE
--watch doesn't seem to regen on yaml updates?

### ISSUE THREAD

**Issue by keitzer** [Tsukumogami-Software/milou#8]
Not sure if this is intended behaviour but when running the build command with `--watch` flag enabled, no amount of `.yml` changes trigger a rebuild.

Even forcing a refresh on the browser doesn't resolve this.
even with `--dev` enabled as well.

Milou v1.1.1, Chrome v125.0.6422.113

**Comment by zer0tonin** [comment]
Milou was still watching for .xml changes. This should be fixed in release 1.20 😀
