### ISSUE TITLE
Lack of custom CSS on build

### ISSUE THREAD

**Issue by keitzer** [Tsukumogami-Software/milou#9]
It's not obvious (or possibly at the moment not possible) to have CSS overrides for the default values. 

is it possible to have an override CSS that gets copied over? for example, I personally think the font size is too large and would prefer slightly smaller (eg: 60%/1.6 looks good to me).

But every time i run the build command it would get overwritten by the new css file.

And/or is it possible to expose the CSS that gets used in generation and just copy that file directly? With possibly a command like `milou generate css` to generate a fresh one in case i mess up badly lol

**Comment by zer0tonin** [comment]
@keitzer thanks for the suggestion. With milou 1.3.1, you can just add a `style.css` at the root of your data folder (alongside your company `data.yml`) and it will be included as a stylesheet in your press kit.
